name: Provision Kafka

on:
#  push:
#    branches:
#      - develop
#    tags:
#      - rc-*
#      - v*
#    paths:
#      - asyncapi.yml
#      - avro/**
#      - .github/workflows/provision-kafka.yml
#  pull_request:
#    branches:
#      - develop
#    paths:
#      - asyncapi.yml
#      - avro/**
#      - .github/workflows/provision-kafka.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  provision-kafka:
    uses: arcadia-editions/api-product-workflows/.github/workflows/provision-kafka-develop.yml@main
    with:
      service_repo: orders-checkout-api
      pipeline_ref: main
    secrets: inherit
